;;; smarty-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from smarty-mode.el

(setq auto-mode-alist (append '(("\\.tpl\\'" . smarty-mode)) auto-mode-alist))
(autoload 'smarty-mode "smarty-mode" "\
Major mode for editing Smarty template files" t)
(register-definition-prefixes "smarty-mode" '("smarty-"))

;;; End of scraped data

(provide 'smarty-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; smarty-mode-autoloads.el ends here
