;;; windswap-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from windswap.el

(autoload 'windswap-default-keybindings "windswap" "\
Set up keybindings for `windswap'.
Keybindings are of the form MODIFIERS-{left,right,up,down}.
Default MODIFIERS are `meta' and `shift'.
See also `windmove-default-keybindings'.

(fn &rest MODIFIERS)" t)
(autoload 'windswap-right "windswap" "\
Like `windmove-right', but transpose buffers after switching windows.
ARG is as for that function.

(fn &optional ARG)" t)
(autoload 'windswap-left "windswap" "\
Like `windmove-left', but transpose buffers after switching windows.
ARG is as for that function.

(fn &optional ARG)" t)
(autoload 'windswap-up "windswap" "\
Like `windmove-up', but transpose buffers after switching windows.
ARG is as for that function.

(fn &optional ARG)" t)
(autoload 'windswap-down "windswap" "\
Like `windmove-down', but transpose buffers after switching windows.
ARG is as for that function.

(fn &optional ARG)" t)
(register-definition-prefixes "windswap" '("windswap--"))

;;; End of scraped data

(provide 'windswap-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; windswap-autoloads.el ends here
