;;; j-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from j-console.el

(autoload 'j-console "j-console" "\
Ensures a running j-console-cmd session and switches focus to
the containing buffer" t)
(register-definition-prefixes "j-console" '("inferior-j-mode" "j-console-"))


;;; Generated autoloads from j-font-lock.el

(register-definition-prefixes "j-font-lock" '("j-"))


;;; Generated autoloads from j-help.el

(autoload 'j-help-lookup-symbol "j-help" "\
Lookup symbol in dictionary

(fn SYMBOL)" t)
(autoload 'j-help-lookup-symbol-at-point "j-help" "\
Determine the symbol nearest to POINT and look it up in the dictionary

(fn POINT)" t)
(register-definition-prefixes "j-help" '("j-help-"))


;;; Generated autoloads from j-mode.el

(autoload 'j-mode "j-mode" "\
Major mode for editing J.

(fn)" t)
(autoload 'j-lab-mode "j-mode" "\
Mojor mode for J Labs.

(fn)" t)
(add-to-list 'auto-mode-alist '("\\.ij[rsp]$" . j-mode))
(add-to-list 'auto-mode-alist '("\\.ijt$" . j-lab-mode))
(register-definition-prefixes "j-mode" '("j-"))

;;; End of scraped data

(provide 'j-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; j-mode-autoloads.el ends here
