;;; just-ts-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from just-ts-mode.el

(autoload 'just-ts-mode "just-ts-mode" "\
Major mode for editing standard Justfiles using treesitter.

(fn)" t)
(add-to-list 'auto-mode-alist '("/[Jj]ustfile\\'" . just-ts-mode))
(add-to-list 'auto-mode-alist '("\\.[Jj]ust\\(file\\)?\\'" . just-ts-mode))
(register-definition-prefixes "just-ts-mode" '("just-ts-"))

;;; End of scraped data

(provide 'just-ts-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; just-ts-mode-autoloads.el ends here
