;;; regex-tool-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from regex-tool.el

(autoload 'regex-tool "regex-tool" nil t)
(register-definition-prefixes "regex-tool" '("regex-"))

;;; End of scraped data

(provide 'regex-tool-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; regex-tool-autoloads.el ends here
