;;; uiua-ts-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from uiua-ts-mode.el

(autoload 'uiua-ts-mode "uiua-ts-mode" "\
Major mode for editing Uiua files.
Uses tree-sitter.

(fn)" t)
(register-definition-prefixes "uiua-ts-mode" '("uiua-ts--"))

;;; End of scraped data

(provide 'uiua-ts-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; uiua-ts-mode-autoloads.el ends here
