;;; osx-location-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from osx-location.el

(autoload 'osx-location-watch "osx-location" "\
Run the helper program in a buffer and respond to its output." t)
(register-definition-prefixes "osx-location" '("osx-location-"))

;;; End of scraped data

(provide 'osx-location-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; osx-location-autoloads.el ends here
