;;; nixfmt-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from nixfmt.el

 (autoload 'nixfmt-buffer "nixfmt" nil t)
 (autoload 'nixfmt-region "nixfmt" nil t)
 (autoload 'nixfmt-on-save-mode "nixfmt" nil t)
(register-definition-prefixes "nixfmt" '("nixfmt-command"))

;;; End of scraped data

(provide 'nixfmt-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; nixfmt-autoloads.el ends here
