;;; immortal-scratch-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from immortal-scratch.el

(defvar immortal-scratch-mode nil "\
Non-nil if Immortal-Scratch mode is enabled.
See the `immortal-scratch-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `immortal-scratch-mode'.")
(custom-autoload 'immortal-scratch-mode "immortal-scratch" nil)
(autoload 'immortal-scratch-mode "immortal-scratch" "\
When the scratch buffer is killed, immediately respawn it.

This is a global minor mode.  If called interactively, toggle the
`Immortal-Scratch mode' mode.  If the prefix argument is positive,
enable the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='immortal-scratch-mode)'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "immortal-scratch" '("immortal-scratch-"))

;;; End of scraped data

(provide 'immortal-scratch-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; immortal-scratch-autoloads.el ends here
