;;; flymake-flycheck-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from flymake-flycheck.el

(autoload 'flymake-flycheck-all-available-diagnostic-functions "flymake-flycheck" "\
Return a list of diagnostic functions for all usable checkers.
These might end up providing duplicate functionality, e.g. both
dash and bash might be used to check a `sh-mode' buffer if both are
found to be installed.

Usually you will want to use `flymake-flycheck-all-chained-diagnostic-functions' instead.")
(autoload 'flymake-flycheck-all-chained-diagnostic-functions "flymake-flycheck" "\
Return a list of diagnostic functions for the current checker chain.")
(autoload 'flymake-flycheck-auto "flymake-flycheck" "\
Activate all available flycheck checkers in the current buffer.")
(autoload 'flymake-flycheck-diagnostic-function-for "flymake-flycheck" "\
Wrap CHECKER to make a `flymake-diagnostics-functions' backend.

(fn CHECKER)")
(register-definition-prefixes "flymake-flycheck" '("flymake-flycheck-"))

;;; End of scraped data

(provide 'flymake-flycheck-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; flymake-flycheck-autoloads.el ends here
