;;; flymake-actionlint-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from flymake-actionlint.el

(autoload 'flymake-actionlint-load "flymake-actionlint" "\
Load Flymake handler for `actionlint'." t)
(autoload 'flymake-actionlint-actions-file-p "flymake-actionlint" "\
Return non-nil iff FILENAME is a yaml file for GitHub Actions.

(fn FILENAME)")
(autoload 'flymake-actionlint-action-load-when-actions-file "flymake-actionlint" "\
Load Flymake handler when current file is yaml file for GitHub Actions.")
(register-definition-prefixes "flymake-actionlint" '("flymake-actionlint-"))

;;; End of scraped data

(provide 'flymake-actionlint-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; flymake-actionlint-autoloads.el ends here
