;;; bug-reference-github-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from bug-reference-github.el

(autoload 'bug-reference-github-set-url-format "bug-reference-github" "\
Automatically set `bug-reference-url-format'.
Automatically set `bug-reference-url-format' and enable
function `bug-reference-prog-mode' buffers from Github repositories.

What it does is:

1. If `bug-reference-url-format' is not set and this appears to be
    part of a git working copy (we can locate a .git/config).

2. Find the git remote repository (run 'git ls-remote --get-url').

3. If the remote matches github.com set `bug-reference-url-format' to
    the correct Github issue URL (we set it buffer locally).

4. Enable function `bug-reference-prog-mode'.")
(register-definition-prefixes "bug-reference-github" '("bug-reference-github-domains"))

;;; End of scraped data

(provide 'bug-reference-github-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; bug-reference-github-autoloads.el ends here
