;;; cljsbuild-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from cljsbuild-mode.el

(autoload 'cljsbuild-mode "cljsbuild-mode" "\
ClojureScript Build mode

This is a minor mode.  If called interactively, toggle the `Cljsbuild
mode' mode.  If the prefix argument is positive, enable the mode, and if
it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `cljsbuild-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(autoload 'cljsbuild-start "cljsbuild-mode" "\
Runs cljsbuild.

(fn COMMAND)" t)
(register-definition-prefixes "cljsbuild-mode" '("cljsbuild-"))

;;; End of scraped data

(provide 'cljsbuild-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; cljsbuild-mode-autoloads.el ends here
