;;; java-snippets-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from java-snippets.el

(autoload 'java-snippets-initialize "java-snippets")
(eval-after-load 'yasnippet '(java-snippets-initialize))
(register-definition-prefixes "java-snippets" '("java-snippets-root"))

;;; End of scraped data

(provide 'java-snippets-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; java-snippets-autoloads.el ends here
