;;; uiua-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from uiua-mode.el

 (autoload 'uiua-format-buffer "uiua-mode" nil t)
 (autoload 'uiua-format-on-save-mode "uiua-mode" nil t)
(autoload 'uiua-base-mode "uiua-mode" "\
Generic Major mode for editing Uiua files.

(fn)" t)
(autoload 'uiua-mode "uiua-mode" "\
Major mode for editing Uiua files.

(fn)" t)
(add-to-list 'auto-mode-alist '("\\.ua\\'" . uiua-mode))
(register-definition-prefixes "uiua-mode" '("uiua-"))

;;; End of scraped data

(provide 'uiua-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; uiua-mode-autoloads.el ends here
