;;; ocaml-ts-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from ocaml-ts-mode.el

(autoload 'ocaml-ts-mode "ocaml-ts-mode" "\
Major mode for editing OCaml, powered by tree-sitter.

(fn)" t)
(autoload 'ocamli-ts-mode "ocaml-ts-mode" "\
Major mode for editing OCaml, powered by tree-sitter.

(fn)" t)
(autoload 'ocaml-ts-mode-install-grammar "ocaml-ts-mode" "\
Install tree-sitter-ocaml grammars." t)
(add-to-list 'auto-mode-alist '("\\.ml\\'" . ocaml-ts-mode))
(add-to-list 'auto-mode-alist '("\\.mli\\'" . ocamli-ts-mode))
(register-definition-prefixes "ocaml-ts-mode" '("ocaml-ts-mode-"))

;;; End of scraped data

(provide 'ocaml-ts-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; ocaml-ts-mode-autoloads.el ends here
