;;; ruby-hash-syntax-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from ruby-hash-syntax.el

(autoload 'ruby-hash-syntax-toggle "ruby-hash-syntax" "\
Toggle syntax of ruby hash literal in region from BEG to END between ruby 1.8 and 1.9 styles.

(fn BEG END)" t)
(register-definition-prefixes "ruby-hash-syntax" '("ruby-hash-syntax--"))

;;; End of scraped data

(provide 'ruby-hash-syntax-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; ruby-hash-syntax-autoloads.el ends here
