;;; dune-format-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from dune-format.el

 (autoload 'dune-format-buffer "dune-format" nil t)
 (autoload 'dune-format-region "dune-format" nil t)
 (autoload 'dune-format-on-save-mode "dune-format" nil t)

;;; End of scraped data

(provide 'dune-format-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; dune-format-autoloads.el ends here
