;;; nixpkgs-fmt-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from nixpkgs-fmt.el

 (autoload 'nixpkgs-fmt-buffer "nixpkgs-fmt" nil t)
 (autoload 'nixpkgs-fmt-region "nixpkgs-fmt" nil t)
 (autoload 'nixpkgs-fmt-on-save-mode "nixpkgs-fmt" nil t)
(register-definition-prefixes "nixpkgs-fmt" '("nixpkgs-fmt-command"))

;;; End of scraped data

(provide 'nixpkgs-fmt-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; nixpkgs-fmt-autoloads.el ends here
